{asite_disp_length_file: /exports/csce/eddie/biology/groups/wallace_rna/riboviz-david/riboviz/riboviz/data/yeast_standard_asite_disp_length.txt,
  codon_positions_file: /exports/csce/eddie/biology/groups/wallace_rna/riboviz-david/riboviz/riboviz/data/yeast_codon_pos_i200.RData,
  features_file: /exports/csce/eddie/biology/groups/wallace_rna/riboviz-david/riboviz/riboviz/data/yeast_features.tsv,
  t_rna_file: /exports/csce/eddie/biology/groups/wallace_rna/riboviz-david/riboviz/riboviz/data/yeast_tRNAs.tsv}

