provenance:
  yaml authors:
  - author: Edward W. J. Wallace
    email: edward.wallace@ed.ac.uk
website:
  date run: 2020-11-06
  riboviz-version: 2.0 | COMMIT d8215697a5fca37df51fd2b71af51e211ac213d2
  GEO: GSM1825740
  reference: Codon Usage Influences the Local Rate of Translation Elongation to Regulate Co-translational Protein Folding., Yu et al. 2015
  DOI: https://doi.org/10.1016/j.molcel.2015.07.018
  notes: Presumes example-datasets folder structure is held within $HOME/riboviz and will need to create folder called Yu_2015_Nc/input to place the .fastq files in, while output and other folders will be created in Yu_2015_Nc/ by the riboviz workflow.

adapters: AGATCGGAAGAGCACACGTCT
aligner: hisat2
asite_disp_length_file: data/yeast_standard_asite_disp_length.txt
buffer: 120
build_indices: true
cmd_file: run_riboviz_Yu_2015_Nc.sh
codon_positions_file: null
count_reads: true
count_threshold: 64
dataset: Yu2015
dedup_stats: false
dedup_umis: false
dir_index: Yu_2015_Nc/index # Built indices directory
dir_in: Yu_2015_Nc/input # Input directory
dir_logs: Yu_2015_Nc/logs # Log files directory
dir_out: Yu_2015_Nc/output # Output directory
dir_tmp: Yu_2015_Nc/tmp # Intermediate files directory
do_pos_sp_nt_freq: false
extract_umis: false
features_file: null
fq_files:
  Cwt-Opt: SRR2105980.fastq.gz
  Opt: SRR2105979.fastq.gz
  WT: SRR2105977.fastq.gz
group_umis: false
is_riboviz_gff: true
is_test_run: false
make_bedgraph: true
max_read_length: 50
min_read_length: 10
multiplex_fq_files: null
num_processes: 2
orf_fasta_file: ../../riboviz/example-datasets/fungi/neurospora/annotation/NC12_CDS_with_120bputrs.fa
orf_gff_file:  ../../riboviz/example-datasets/fungi/neurospora/annotation/NC12_CDS_120bpL_120bpR.gff3
orf_index_prefix: NC12_CDS_with_120bputrs
primary_id: Name
publish_index_tmp: false
rpf: true
rrna_fasta_file: ../../riboviz/example-datasets/fungi/neurospora/contaminants/Neurospora_crassa_NC12_rRNA_tRNA.fa
rrna_index_prefix: NC12_rRNA_tRNA
sample_sheet: null
secondary_id: null
stop_in_cds: true
t_rna_file: null
umi_regexp: null
