provenance:
  DOI: null
  GEO: null
  date run: 2021-01-12
  notes: Simulated data from Amanda Mok, January 2021
  reference: simRiboSeq, https://github.com/amandamok/simRiboSeq/, Amanda Mok 2021
    commit 48c9e2d
  riboviz-version: 2.0 | 8e61429
  website: null
  yaml authors:
  - author: Edward Wallace
    email: Edward.Wallace@ed.ac.uk

adapters: CTGTAGGCACCATCAAT
asite_disp_length_file: data/yeast_standard_asite_disp_length.txt
buffer: 250
build_indices: true
codon_positions_file: data/yeast_codon_pos_i200.RData
count_reads: true
count_threshold: 64
dataset: Mok-simYAL5
dedup_stats: false
dedup_umis: false
dir_in: Mok-simYAL5/input
dir_index: Mok-simYAL5/index
dir_out: Mok-simYAL5/output
dir_tmp: Mok-simYAL5/tmp
do_pos_sp_nt_freq: true
extract_umis: false
feature: CDS
features_file: null
fq_files:
  A: simRiboviz.fq.gz
group_umis: false
is_riboviz_gff: true
job_email: null
job_email_events: beas
job_memory: 8G
job_name: riboviz
job_num_cpus: 4
job_parallel_env: mpi
job_runtime: '48:00:00'
make_bedgraph: true
max_read_length: 50
min_read_length: 10
multiplex_fq_files: null
nextflow_dag_file: nextflow-dag.html
nextflow_report_file: nextflow-report.html
nextflow_timeline_file: nextflow-timeline.html
nextflow_trace_file: nextflow-trace.tsv
nextflow_work_dir: work
num_processes: 1
orf_fasta_file: ../../riboviz/example-datasets/simulated/mok/annotation/Scer_YAL_5genes_w_250utrs.fa
orf_gff_file: ../../riboviz/example-datasets/simulated/mok/annotation/Scer_YAL_5genes_w_250utrs.gff3
orf_index_prefix: Scer_YAL_5genes
output_pdfs: true
primary_id: Name
publish_index_tmp: false
rpf: true
rrna_fasta_file: ../../riboviz/example-datasets/fungi/saccharomyces/contaminants/Saccharomyces_cerevisiae_yeast_rRNA_R64-1-1.fa
rrna_index_prefix: yeast_rRNA
run_static_html: true
sample_sheet: null
samsort_memory: null
secondary_id: null
stop_in_feature: false
t_rna_file: data/yeast_tRNAs.tsv
trim_5p_mismatches: true
umi_regexp: null
validate_only: false
