Provenance:
  yaml authors:
  - author: Felicity Anderson
    email: Felicity.Anderson@ed.ac.uk
  - author: Sophie Winterbourne
    email: '...'
  date run: 2021-02-19
  riboviz-version: 2.0 | COMMIT e94a909c70942cb428450a3b98edef1614143c18
  assession number: GSE61012
  reference: Principles of ER cotranslational translocation revealed by proximity-specific ribosome profiling, Jan et al. 2014.
  DOI: https://doi.org/10.1126/science.1257521
  notes: Run assuming no UMIs. Analysis of 1 RPF sample of S. cerevisiae which was used by Gamble et al 2016 to identify inhibitory codon pairs.
  riboviz environment tokens use: for advice on how to use environment tokens with riboviz, see documentation at https://github.com/riboviz/riboviz/blob/main/docs/user/prep-riboviz-config.md#environment-variables-and-configuration-tokens
  riboviz environment tokens note 1: ${RIBOVIZ_DATA} should point to riboviz repo data folder location e.g. /home/user/riboviz/riboviz/data
  riboviz environment tokens note 2: ${RIBOVIZ_ORGANISMS} is location of example-datasets repository folder e.g. /home/user/riboviz/example-datasets
  riboviz environment tokens note 3: ${RIBOVIZ_SAMPLES} should point to location where input data fastq file has been downloaded from simRiboSeq/simulation_runs/riboviz repository folder & placed within 'input' folder
  
adapters: CTGTAGGCACCATCAAT
asite_disp_length_file: ${RIBOVIZ_DATA}/yeast_standard_asite_disp_length.txt
buffer: 250
build_indices: true
codon_positions_file: ${RIBOVIZ_DATA}/yeast_codon_pos_i200.RData
count_reads: true
count_threshold: 64
dataset: J-Sc-2014
dedup_stats: false
dedup_umis: false
dir_in: ${RIBOVIZ_SAMPLES}/input
dir_index: ${RIBOVIZ_SAMPLES}/index
dir_out: ${RIBOVIZ_SAMPLES}/output
dir_tmp: ${RIBOVIZ_SAMPLES}/tmp
extract_umis: false
features_file: ${RIBOVIZ_DATA}/yeast_features.tsv
fq_files:
  sec63_1: SRR1562907.fastq.gz
group_umis: false
is_riboviz_gff: true
make_bedgraph: true
max_read_length: 50
min_read_length: 10
multiplex_fq_files: null
num_processes: 16
orf_fasta_file: ${RIBOVIZ_ORGANISMS}/fungi/saccharomyces/annotation/Saccharomyces_cerevisiae_yeast_CDS_w_250utrs.fa
orf_gff_file: ${RIBOVIZ_ORGANISMS}/fungi/saccharomyces/annotation/Saccharomyces_cerevisiae_yeast_CDS_w_250utrs.gff3
orf_index_prefix: yeast_CDS_w_250
primary_id: Name
publish_index_tmp: false
rpf: true
rrna_fasta_file: 
orf_fasta_file: ${RIBOVIZ_ORGANISMS}/fungi/saccharomyces/contaminants/Saccharomyces_cerevisiae_yeast_rRNA_R64-1-1.fa
rrna_index_prefix: yeast_rRNA
samsort_memory: 768M
sample_sheet: null
secondary_id: null
skip_inputs: false
trim_5p_mismatches: true
t_rna_file: ${RIBOVIZ_DATA}/yeast_tRNAs.tsv
umi_regexp: null
validate_only: false
stop_in_feature: false
output_metagene_normalized_profile: true
feature: CDS
hisat2_orf_params: -k 2 --no-spliced-alignment --rna-strandness F --no-unal
job_email: null
job_email_events: beas
job_memory: 8G
job_name: riboviz
job_num_cpus: 4
job_parallel_env: mpi
job_runtime: '48:00:00'
nextflow_dag_file: nextflow-dag.html
nextflow_report_file: nextflow-report.html
nextflow_timeline_file: nextflow-timeline.html
nextflow_trace_file: nextflow-trace.tsv
nextflow_work_dir: work
output_pdfs: true
run_static_html: true
