provenance:
  yaml authors:
  - author: Felicity Anderson
    email: Felicity.Anderson@ed.ac.uk
  - author: Sophie Winterbourne
    email: '...'
  website: null
  date run: 2021-02-21
  riboviz-version: 2.0 | COMMIT e94a909c70942cb428450a3b98edef1614143c18
  GEO: GSE58321
  reference: Distinct stages of the translation elongation cycle revealed by sequencing
    ribosome-protected mRNA fragments, Lareau et. al. 2014
  DOI: https://doi.org/10.7554/eLife.01257
  notes: Replicates carried out by Gamble et al 2016 to confirm findings of ICPs from
    Jan et al 2014.
adapters: CTGTAGGCACCATCAAT
asite_disp_length_file: data/yeast_standard_asite_disp_length.txt
buffer: 250
build_indices: true
codon_positions_file: data/yeast_codon_pos_i200.RData
count_reads: true
count_threshold: 64
dataset: L-Sc_2014
dedup_stats: false
dedup_umis: false
dir_in: L-Sc_2014/input
dir_index: L-Sc_2014/index
dir_out: L-Sc_2014/output
dir_tmp: L-Sc_2014/tmp
extract_umis: false
features_file: data/yeast_features.tsv
fq_files:
  Replicate-1: SRR1363412.fastq.gz
  Replicate-2: SRR1363413.fastq.gz
  Replicate-3: SRR1363414.fastq.gz
group_umis: false
is_riboviz_gff: true
make_bedgraph: true
max_read_length: 50
min_read_length: 10
multiplex_fq_files: null
num_processes: 16
orf_fasta_file: ../../riboviz/example-datasets/fungi/saccharomyces/annotation/Saccharomyces_cerevisiae_yeast_CDS_w_250utrs.fa
orf_gff_file: ../../riboviz/example-datasets/fungi/saccharomyces/annotation/Saccharomyces_cerevisiae_yeast_CDS_w_250utrs.gff3
orf_index_prefix: yeast_CDS_w_250
primary_id: Name
publish_index_tmp: false
rpf: true
rrna_fasta_file: ../../riboviz/example-datasets/fungi/saccharomyces/contaminants/Saccharomyces_cerevisiae_yeast_rRNA_R64-1-1.fa
rrna_index_prefix: yeast_rRNA
samsort_memory: 768M
sample_sheet: null
secondary_id: null
skip_inputs: false
trim_5p_mismatches: true
t_rna_file: data/yeast_tRNAs.tsv
umi_regexp: null
validate_only: false
stop_in_feature: false
output_metagene_normalized_profile: true
feature: CDS
hisat2_orf_params: -k 2 --no-spliced-alignment --rna-strandness F --no-unal
job_email: null
job_email_events: beas
job_memory: 8G
job_name: riboviz
job_num_cpus: 4
job_parallel_env: mpi
job_runtime: '48:00:00'
nextflow_dag_file: nextflow-dag.html
nextflow_report_file: nextflow-report.html
nextflow_timeline_file: nextflow-timeline.html
nextflow_trace_file: nextflow-trace.tsv
nextflow_work_dir: work
output_pdfs: true
run_static_html: true
