provenance:
  DOI: https://doi.org/10.1016/j.celrep.2016.01.043
  GEO: GSE75897
  date run: 2021-02-12
  notes: S. cerevisiae RPF dataset for riboviz hackathon by Emma and Sophie.
  reference: Improved ribosome-footprint and mRNA measurements provide insights into
    dynamics and regulation of yeast translation, Weinberg et al. 2016
  riboviz-version: 2.0 | COMMIT 7e62c9f8da4f66f9c18aca30394f44fa4a7fa1ef
  website: null
  yaml authors:
  - author: Felicity Anderson
    email: Felicity.Anderson@ed.ac.uk
  - author: Emma MacKenzie
    email: '...'
  - author: Sophie Winterbourne
    email: '...'


adapters: TCGTATGCCGTCTTCTGCTTG
asite_disp_length_file: data/yeast_standard_asite_disp_length.txt
buffer: 250
build_indices: true
codon_positions_file: data/yeast_codon_pos_i200.RData
count_reads: true
count_threshold: 64
dataset: W-Sc_2016
dedup_stats: true
dedup_umis: true
dir_in: W-Sc_2016/input
dir_index: W-Sc_2016/index
dir_out: W-Sc_2016/output
dir_tmp: W-Sc_2016/tmp
do_pos_sp_nt_freq: true
extract_umis: true
feature: CDS
features_file: data/yeast_features.tsv
fq_files:
  Cerevisiae_RPF: SRR1049521.fastq.gz
group_umis: true
is_riboviz_gff: true
job_email: null
job_email_events: beas
job_memory: 8G
job_name: riboviz
job_num_cpus: 4
job_parallel_env: mpi
job_runtime: '48:00:00'
make_bedgraph: true
max_read_length: 50
min_read_length: 10
multiplex_fq_files: null
nextflow_dag_file: nextflow-dag.html
nextflow_report_file: nextflow-report.html
nextflow_timeline_file: nextflow-timeline.html
nextflow_trace_file: nextflow-trace.tsv
nextflow_work_dir: work
num_processes: 16
orf_fasta_file: ../../riboviz/example-datasets/fungi/saccharomyces/annotation/Saccharomyces_cerevisiae_yeast_CDS_w_250utrs.fa
orf_gff_file: ../../riboviz/example-datasets/fungi/saccharomyces/annotation/Saccharomyces_cerevisiae_yeast_CDS_w_250utrs.gff3
orf_index_prefix: yeast_CDS_w_250
output_pdfs: true
primary_id: Name
publish_index_tmp: false
rpf: true
rrna_fasta_file: ../../riboviz/example-datasets/fungi/saccharomyces/contaminants/Saccharomyces_cerevisiae_yeast_rRNA_R64-1-1.fa
rrna_index_prefix: yeast_rRNA
run_static_html: true
sample_sheet: null
samsort_memory: 768M
secondary_id: null
skip_inputs: false
stop_in_feature: false
t_rna_file: data/yeast_tRNAs.tsv
trim_5p_mismatches: true
umi_regexp: (?P<umi_1>.{8})
validate_only: false
