provenance:
  yaml authors:
  - author: Felicity Anderson
    email: Felicity.Anderson@ed.ac.uk
  - author: Emma MacKenzie
    email: ...
  - author: Sophie Winterbourne
    email: ...
  website:
  date run: 2021-02-12
  riboviz-version: 2.0 | COMMIT 7e62c9f8da4f66f9c18aca30394f44fa4a7fa1ef
  GEO: GSE75897
  reference: Improved ribosome-footprint and mRNA measurements provide insights into dynamics and regulation of yeast translation, Weinberg et al. 2016
  DOI: https://doi.org/10.1016/j.celrep.2016.01.043
  notes: S. cerevisiae RPF dataset for riboviz hackathon by Emma and Sophie. 

adapters: TCGTATGCCGTCTTCTGCTTG # Illumina sequencing adapter(s) to remove
aligner: hisat2 # Short read aligner to use. Currently only hisat2 works
asite_disp_length_file: data/yeast_standard_asite_disp_length.txt # Table of fixed A-site positions by read length
buffer: 250 # Length of flanking region around the CDS
build_indices: true # Build indices for aligner? if TRUE, remake indices from fasta files
cmd_file: run_riboviz_W-Sc_2016.sh # Bash commands file
codon_positions_file: data/yeast_codon_pos_i200.RData # Codon positions in each gene
count_reads: true # Scan input, temporary and output files and produce counts of reads in each FASTQ, SAM, and BAM file processed?
count_threshold: 64 # Remove genes with a read count below this threshold, when generating statistics and figures
dataset: W-Sc_2016 # Dataset name
dedup_stats: TRUE # Output UMI deduplication statistics?
dedup_umis: TRUE # Extract UMIs and deduplicate reads if TRUE
dir_in: W-Sc_2016/input # Input directory
dir_index: W-Sc_2016/index # Built indices directory
dir_logs: W-Sc_2016/logs # Log files directory
dir_out: W-Sc_2016/output # Output directory
dir_tmp: W-Sc_2016/tmp # Intermediate files directory
do_pos_sp_nt_freq: true # Calculate position-specific nucleotide frequency?
extract_umis: TRUE # Extract UMIs if TRUE
features_file: data/yeast_features.tsv # Features to correlate with ORFs
fq_files: # fastq files to be processed, relative to dir_in
  Cerevisiae_RPF: SRR1049521.fastq.gz
group_umis: TRUE # Summarise UMI groups before and after deduplication, if TRUE
is_riboviz_gff: true # Does the GFF file contain 3 elements per gene - UTR5, CDS, and UTR3
is_test_run: false # Is this a test run
make_bedgraph: true # Output bedgraph files, as TSV, in addition to h5?
max_read_length: 50 # Maximum read length in H5 output
min_read_length: 10 # Minimum read length in H5 output
multiplex_fq_files: null # Multiplexed fastq files to be processed, relative to dir_in
num_processes: 16 # Number of processes to parallelize over
orf_fasta_file: ../../riboviz/example-datasets/fungi/saccharomyces/annotation/Saccharomyces_cerevisiae_yeast_CDS_w_250utrs.fa # ORF file to align to
orf_gff_file: ../../riboviz/example-datasets/fungi/saccharomyces/annotation/Saccharomyces_cerevisiae_yeast_CDS_w_250utrs.gff3 # GFF2/GFF3 file for ORFs
orf_index_prefix: yeast_CDS_w_250 # ORF index file prefix, relative to dir_index
primary_id: Name # Primary gene IDs to access the data (YAL001C, YAL003W, etc.)
publish_index_tmp: FALSE
rpf: true # Is the dataset an RPF or mRNA dataset?
rrna_fasta_file: ../../riboviz/example-datasets/fungi/saccharomyces/contaminants/Saccharomyces_cerevisiae_yeast_rRNA_R64-1-1.fa # rRNA file to avoid aligning to
rrna_index_prefix: yeast_rRNA # rRNA index file prefix, relative to dir_index
samsort_memory: 768M
sample_sheet: null # Sample sheet, TSV file with, at least, SampleID and TagRead (barcode) columns
secondary_id: null # Secondary gene IDs to access the data (COX1, EFB1, etc.)
skip_inputs: FALSE
stop_in_cds: FALSE # Are stop codons part of the CDS annotations in GFF?
trim_5p_mismatches: TRUE
t_rna_file: data/yeast_tRNAs.tsv # tRNA estimates
umi_regexp: (?P<umi_1>.{8}) # UMI-tools-compliant regular expression to extract UMIs
validate_only: FALSE
