provenance:
  yaml authors:
  - author: Felicity Anderson
    email: Felicity.Anderson@ed.ac.uk
  - author: Sophie Winterbourne
  DOI: http://dx.doi.org/10.1126/sciadv.aba1306
  GEO: GSE134152
  date run: 2021-02-23
  notes: Ribosome profiling datasets of Saccharomyces cerevisiae grown under glucose
    restriction conditions.
  reference: Life span extension by glucose restriction is abrogated by methionine
    supplementation - Cross-talk between glucose and methionine and implication of
    methionine as a key regulator of life span, Zou et al 2020.
  riboviz-version: 2.0 | COMMIT e94a909c70942cb428450a3b98edef1614143c18
  riboviz environment tokens use: for advice on how to use environment tokens with
    riboviz, see documentation at https://github.com/riboviz/riboviz/blob/main/docs/user/prep-riboviz-config.md#environment-variables-and-configuration-tokens
  riboviz environment tokens note 1: ${RIBOVIZ_DATA} should point to riboviz repo
    data folder location e.g. /home/user/riboviz/riboviz/data
  riboviz environment tokens note 2: ${RIBOVIZ_ORGANISMS} is location of example-datasets
    Saccharomyces genus data repository folder e.g. /home/user/riboviz/example-datasets/fungi/saccharomyces
  riboviz environment tokens note 3: ${RIBOVIZ_SAMPLES} should point to location where
    input data fastq file has been downloaded & placed within 'input' folder e.g.
    /home/user/Z-Sc_2020
adapters: CTGTAGGCACCATCAAT
asite_disp_length_file: ${RIBOVIZ_DATA}/yeast_standard_asite_disp_length.txt
buffer: 250
build_indices: true
codon_positions_file: ${RIBOVIZ_DATA}/yeast_codon_pos_i200.RData
count_reads: true
count_threshold: 64
dataset: Z-Sc_2020
dedup_stats: false
dedup_umis: false
dir_in: ${RIBOVIZ_SAMPLES}/input
dir_index: ${RIBOVIZ_SAMPLES}/index
dir_out: ${RIBOVIZ_SAMPLES}/output
dir_tmp: ${RIBOVIZ_SAMPLES}/tmp
extract_umis: false
feature: CDS
features_file: ${RIBOVIZ_DATA}/yeast_features.tsv
fq_files:
  SD-sample3-1: SRR9670816.fastq.gz
  SD-sample3-2: SRR9670817.fastq.gz
  #GR-sample4-1: SRR9670818.fastq.gz
  #GR-sample4-2: SRR9670819.fastq.gz
  #SD-sample7: SRR9670822.fastq.gz
  #GR-sample8: SRR9670823.fastq.gz
group_umis: false
hisat2_orf_params: -k 2 --no-spliced-alignment --rna-strandness F --no-unal
is_riboviz_gff: true
job_email: null
job_email_events: null
job_memory: null
job_name: riboviz
job_num_cpus: null
job_parallel_env: null
job_runtime: null
make_bedgraph: true
max_read_length: 50
min_read_length: 10
multiplex_fq_files: null
nextflow_dag_file: nextflow-dag.html
nextflow_report_file: nextflow-report.html
nextflow_timeline_file: nextflow-timeline.html
nextflow_trace_file: nextflow-trace.tsv
nextflow_work_dir: Z-Sc_2020/work
num_processes: 1
orf_fasta_file: ${RIBOVIZ_ORGANISMS}/fungi/saccharomyces/annotation/Saccharomyces_cerevisiae_yeast_CDS_w_250utrs.fa
orf_gff_file: ${RIBOVIZ_ORGANISMS}/fungi/saccharomyces/annotation/Saccharomyces_cerevisiae_yeast_CDS_w_250utrs.gff3
orf_index_prefix: yeast_CDS_w_250
output_metagene_normalized_profile: true
output_pdfs: true
primary_id: Name
publish_index_tmp: false
rpf: true
rrna_fasta_file: ${RIBOVIZ_ORGANISMS}/fungi/saccharomyces/contaminants/Saccharomyces_cerevisiae_yeast_rRNA_R64-1-1.fa
rrna_index_prefix: yeast_rRNA
run_static_html: true
sample_sheet: null
samsort_memory: null
secondary_id: null
skip_inputs: false
stop_in_feature: false
t_rna_file: ${RIBOVIZ_DATA}/yeast_tRNAs.tsv
trim_5p_mismatches: true
umi_regexp: null
validate_only: false
