provenance:
  yaml authors:
  - author: Emma MacKenzie
    email: '...'
  - author: Sophie Winterbourne
    email: '...'
  website: null
  date run: 2022/05/30
  riboviz-version: 2.2 | COMMIT a2ebaa7dac383e6ce0972626bf57fdba105d1780
  GEO: GSE68705
  reference: Genome-Wide Reprogramming of Transcript Architecture by Temperature Specifies
    the Developmental States of the Human Pathogen Histoplasma, Sil et al 2015
  DOI: https://doi.org/10.1371/journal.pgen.1005395
  notes: add new species H capsulatum with this data as the first sample run. There
    are some irregularities in the output files, see issue
  riboviz environment tokens use: for advice on how to use environment tokens with riboviz, see documentation at https://github.com/riboviz/riboviz/blob/main/docs/user/prep-riboviz-config.md#environment-variables-and-configuration-tokens
  riboviz environment tokens note 1: ${RIBOVIZ_DATA} should point to riboviz repo data folder location e.g. /home/user/riboviz/riboviz/data
  riboviz environment tokens note 2: ${RIBOVIZ_ORGANISMS} is location of example-datasets simulated data repository folder e.g. /home/user/riboviz/example-datasets/simulated/mok
  riboviz environment tokens note 3: ${RIBOVIZ_SAMPLES} should point to location where input data fastq file has been downloaded from simRiboSeq/simulation_runs/riboviz repository folder & placed within 'input' folder
  
adapters: CTGTAGGCACCATCAAT
asite_disp_length_file: ${RIBOVIZ_DATA}/yeast_standard_asite_disp_length.txt
buffer: 250
build_indices: true
codon_positions_file: null
count_reads: true
count_threshold: 64
dataset: S-Hc_2015
dedup_stats: false
dedup_umis: false
dir_in: ${RIBOVIZ_SAMPLES}/input
dir_index: ${RIBOVIZ_SAMPLES}/index
dir_out: ${RIBOVIZ_SAMPLES}/output
dir_tpm: ${RIBOVIZ_SAMPLES}/tpm
extract_umis: false
feature: CDS
features_file: null
fq_files:
  Hyphae_C: SRR2015208.fastq.gz
  Hyphae_D: SRR2015210.fastq.gz
  Yeast_C: SRR2015212.fastq.gz
  Yeast_D: SRR2015214.fastq.gz
group_umis: false
is_riboviz_gff: true
job_email_events: beas
job_email: null
job_memory: 20G
job_name: riboviz
job_num_cpus: 10
job_parallel_env: sharedmem
job_runtime: 172800
make_bedgraph: true
max_read_length: 50
min_read_length: 10
multiplex_fq_files: null
nextflow_dag_file: nextflow-dag.html
nextflow_report_file: nextflow-report.html
nextflow_timeline_file: nextflow-timeline.html
nextflow_trace_file: nextflow-trace.tsv
nextflow_work_dir: S-Hc_2015/work
num_processes: 16
orf_fasta_file: ${RIBOVIZ_ORGANISMS}/fungi/histoplasma/annotation/Histoplasma_capsulatum_G217B_w_250utrs.fasta
orf_gff_file: ${RIBOVIZ_ORGANISMS}/fungi/histoplasma/annotation/Histoplasma_capsulatum_G217B_w_250utrs.gff3
orf_index_prefix: yeast_CDS_w_250
output_pdfs: true
primary_id: Name
publish_index_tpm: false
rpf: true
rrna_fasta_file: ${RIBOVIZ_ORGANISMS}/fungi/histoplasma/contaminants/Histoplasma_capsulatum_G217B_rRNA_tRNA.fa
rrna_index_prefix: yeast_rRNA
run_static_html: true
samsort_memory: 768M
sample_sheet: null
secondary_id: null
skip_inputs: false
stop_in_feature: false
trim_5p_mismatches: true
t_rna_file: null
umi_regexp: null
validate_only: false
output_metagene_normalized_profile: true
dir_tmp: tmp
hisat2_orf_params: -k 2 --no-spliced-alignment --rna-strandness F --no-unal
publish_index_tmp: false
