provenance:
  Array Express: E-MTAB-5810
  DOI: https://doi.org/10.1073/pnas.1713991115
  date run: 2021-03-08
  notes: S. pombe example dataset by Emma MacKenzie as part of her honours project.
  reference: General amino acid control in fission yeast is regulated by a nonconserved
    transcription factor, with functions analogous to Gcn4/Atf4, Duncan et al, 2018
  riboviz-version: 2.0 | COMMIT b75c1ba0e2a541d6f256e2d295b352a3aef969a9
  yaml authors:
  - author: Emma MacKenzie
    email: '...'


adapters: TGGAATTCTCGGGTGCCAAGG
asite_disp_length_file: null
buffer: 250
build_indices: true
codon_positions_file: null
count_reads: true
count_threshold: 64
dataset: D-Sp_2018
dedup_stats: true
dedup_umis: true
dir_in: D-Sp_2018/input
dir_index: D-Sp_2018/index
dir_out: D-Sp_2018/output
dir_tmp: D-Sp_2018/tmp
do_pos_sp_nt_freq: true
extract_umis: true
feature: CDS
features_file: null
fq_files:
  wt.noAT.ribo.3_s: ERR2003553.fastq.gz
  wt.noAT.ribo.4_s: ERR2003554.fastq.gz
group_umis: true
is_riboviz_gff: true
job_email: null
job_email_events: beas
job_memory: 8G
job_name: riboviz
job_num_cpus: 4
job_parallel_env: mpi
job_runtime: '48:00:00'
make_bedgraph: true
max_read_length: 50
min_read_length: 10
multiplex_fq_files: null
nextflow_dag_file: nextflow-dag.html
nextflow_report_file: nextflow-report.html
nextflow_timeline_file: nextflow-timeline.html
nextflow_trace_file: nextflow-trace.tsv
nextflow_work_dir: work
num_processes: 16
orf_fasta_file: ../../riboviz/example-datasets/fungi/schizosaccharomyces/annotation/Schizosaccharomyces_pombe_CDS_w_250utrs.fasta
orf_gff_file: ../../riboviz/example-datasets/fungi/schizosaccharomyces/annotation/Schizosaccharomyces_pombe_CDS_w_250utrs.gff3
orf_index_prefix: yeast_CDS_w_250
output_pdfs: true
primary_id: Name
publish_index_tmp: false
rpf: true
rrna_fasta_file: ../../riboviz/example-datasets/fungi/schizosaccharomyces/contaminants/schizosaccharomyces_pombe_972h-_rRNA.fasta
rrna_index_prefix: yeast_rRNA
run_static_html: true
sample_sheet: null
samsort_memory: 768M
secondary_id: null
skip_inputs: false
stop_in_feature: false
t_rna_file: null
trim_5p_mismatches: true
umi_regexp: ^(?P<umi_1>.{4}).+(?P<umi_2>.{4})$
validate_only: false
