provenance:
  yaml authors:
  - author: Edward W. J. Wallace
    email: edward.wallace@ed.ac.uk
  - author: Felicity Anderson
    email: Felicity.Anderson@ed.ac.uk
  - author: Siyin Xue
    email: siyinxue@gmail.com
website:
  date run: 2020-09-26
  riboviz-version: 2.0 | COMMIT 0f4e932d8c7de032d66f68048989b182730e7d49
  GEO: GSE133125
  reference: Quantitative global studies reveal differential translational control
    by start codon context across the fungal kingdom, Wallace et al. 2012
  DOI: https://doi.org/10.1093/nar/gkaa060
  notes: Presumes example-datasets folder structure is held within $HOME/riboviz and
    will need to create folder called Wallace_2020_H99/input to place the .fastq files
    in, while output and other folders will be created in Wallace_2020/ by the riboviz
    workflow.
  riboviz environment tokens use: for advice on how to use environment tokens with riboviz, see documentation at https://github.com/riboviz/riboviz/blob/main/docs/user/prep-riboviz-config.md#environment-variables-and-configuration-tokens
  riboviz environment tokens note 1: ${RIBOVIZ_DATA} should point to riboviz repo data folder location e.g. /home/user/riboviz/riboviz/data
  riboviz environment tokens note 2: ${RIBOVIZ_ORGANISMS} is location of example-datasets simulated data repository folder e.g. /home/user/riboviz/example-datasets/simulated/mok
  riboviz environment tokens note 3: ${RIBOVIZ_SAMPLES} should point to location where input data fastq file has been downloaded from simRiboSeq/simulation_runs/riboviz repository folder & placed within 'input' folder
  
adapters: CTGTAGGCACC
asite_disp_length_file: ${RIBOVIZ_DATA}/yeast_standard_asite_disp_length.txt
buffer: 120
build_indices: true
codon_positions_file: null
count_reads: true
count_threshold: 64
dataset: Wallace_2020_H99
dedup_stats: false
dedup_umis: false
dir_index: ${RIBOVIZ_SAMPLES}/index
dir_in: ${RIBOVIZ_SAMPLES}/input
dir_out: ${RIBOVIZ_SAMPLES}/output
dir_tmp: ${RIBOVIZ_SAMPLES}/tmp
extract_umis: false
features_file: null
fq_files:
  H99r1: SRR9336389.fastq.gz
  HdGWO1: SRR9336391.fastq.gz
  H99r2: SRR9336393.fastq.gz
  HdAGO1: SRR9336395.fastq.gz
group_umis: false
is_riboviz_gff: true
make_bedgraph: true
max_read_length: 50
min_read_length: 10
multiplex_fq_files: null
num_processes: 2
orf_fasta_file: ${RIBOVIZ_ORGANISMS}/fungi/cryptococcus/annotation/H99_10p_up12dwn9_CDS_with_120bputrs.fa
orf_gff_file: ${RIBOVIZ_ORGANISMS}/fungi/cryptococcus/annotation/H99_10p_up12dwn9_CDS_120bpL_120bpR.gff3
orf_index_prefix: H99_CDS_with_120bputrs
primary_id: Name
rpf: true
rrna_fasta_file: ${RIBOVIZ_ORGANISMS}/fungi/cryptococcus/contaminants/H99_rrna.fasta
rrna_index_prefix: H99_rRNA
sample_sheet: null
secondary_id: null
t_rna_file: null
umi_regexp: null
stop_in_feature: true
output_metagene_normalized_profile: false
feature: CDS
hisat2_orf_params: -k 2 --no-spliced-alignment --rna-strandness F --no-unal
job_email: null
job_email_events: beas
job_memory: 8G
job_name: riboviz
job_num_cpus: 4
job_parallel_env: mpi
job_runtime: '48:00:00'
nextflow_dag_file: nextflow-dag.html
nextflow_report_file: nextflow-report.html
nextflow_timeline_file: nextflow-timeline.html
nextflow_trace_file: nextflow-trace.tsv
nextflow_work_dir: work
output_pdfs: true
publish_index_tmp: false
run_static_html: true
samsort_memory: null
trim_5p_mismatches: true
validate_only: false
