provenance:
  authors:
  - author: Felicity Anderson
    email: Felicity.Anderson@ed.ac.uk
  website: null
  date run: 2022-05-25
  riboviz-version: 2.2 | COMMIT a2ebaa7dac383e6ce0972626bf57fdba105d1780
  GEO: GSE52236
  reference: Extensive and coordinated control of allele-specific expression by both
    transcription and translation in Candida albicans. Genome Res 2014 Jun;24(6):963-73.
    Muzzey D, Sherlock G, Weissman JS.
  DOI: https://doi.org/10.1101/gr.166322.113
  notes: Candida albicans RPF dataset (2 bio reps, one with 2 technical reps)
  riboviz environment tokens use: for advice on how to use environment tokens with riboviz, see documentation at https://github.com/riboviz/riboviz/blob/main/docs/user/prep-riboviz-config.md#environment-variables-and-configuration-tokens
  riboviz environment tokens note 1: ${RIBOVIZ_DATA} should point to riboviz repo data folder location e.g. /home/user/riboviz/riboviz/data
  riboviz environment tokens note 2: ${RIBOVIZ_ORGANISMS} is location of example-datasets simulated data repository folder e.g. /home/user/riboviz/example-datasets/simulated/mok
  riboviz environment tokens note 3: ${RIBOVIZ_SAMPLES} should point to location where input data fastq file has been downloaded from simRiboSeq/simulation_runs/riboviz repository folder & placed within 'input' folder
  
adapters: CTGTAGGCACCATCAAT
asite_disp_length_file: ${RIBOVIZ_DATA}/yeast_standard_asite_disp_length.txt
buffer: 120
build_indices: true
codon_positions_file: null
count_reads: true
count_threshold: 64
dataset: M-Ca_2014
dedup_stats: false
dedup_umis: false
dir_in: ${RIBOVIZ_SAMPLES}/input
dir_index: ${RIBOVIZ_SAMPLES}/index
dir_out: ${RIBOVIZ_SAMPLES}/output
dir_tmp: ${RIBOVIZ_SAMPLES}/tmp
extract_umis: false
features_file: null
fq_files:
  WT_A: SRR1027794.fastq.gz
  WT_A2: SRR1027795.fastq.gz
  WT_B: SRR1027796.fastq.gz
group_umis: false
is_riboviz_gff: true
make_bedgraph: true
max_read_length: 50
min_read_length: 10
multiplex_fq_files: null
num_processes: 8
orf_fasta_file: ${RIBOVIZ_ORGANISMS}/fungi/candida/annotation/Candida_albicans_CDS_with_120utrs.fa
orf_gff_file: ${RIBOVIZ_ORGANISMS}/fungi/candida/annotation/Candida_albicans_CDS_with_120utrs.gff3
orf_index_prefix: CAlbi_CDS_with_120utrs
primary_id: Name
publish_index_tmp: false
rpf: true
rrna_fasta_file: ${RIBOVIZ_ORGANISMS}/fungi/candida/contaminants/Candida_albicans_rRNA_tRNA.fa
rrna_index_prefix: Calbicans_rRNA_tRNA
sample_sheet: null
secondary_id: null
t_rna_file: null
trim_5p_mismatches: true
umi_regexp: null
stop_in_feature: true
output_metagene_normalized_profile: false
feature: CDS
hisat2_orf_params: -k 2 --no-spliced-alignment --rna-strandness F --no-unal
job_email: null
job_email_events: beas
job_memory: 8G
job_name: riboviz
job_num_cpus: 4
job_parallel_env: mpi
job_runtime: '48:00:00'
nextflow_dag_file: nextflow-dag.html
nextflow_report_file: nextflow-report.html
nextflow_timeline_file: nextflow-timeline.html
nextflow_trace_file: nextflow-trace.tsv
nextflow_work_dir: work
output_pdfs: true
run_static_html: true
samsort_memory: null
validate_only: false
