provenance:
  authors:
  - author: Felicity Anderson
    email: Felicity.Anderson@ed.ac.uk
  website:
  date run: 2020-04-28
  riboviz-version: 2.0 | COMMIT
  GEO: GSE52236
  reference: Extensive and coordinated control of allele-specific expression by both transcription and translation in Candida albicans. Genome Res 2014 Jun;24(6):963-73. Muzzey D, Sherlock G, Weissman JS.
  DOI: https://doi.org/10.1101/gr.166322.113
  notes: Candida albicans RPF dataset (2 bio reps, one with 2 technical reps)

adapters: CTGTAGGCACCATCAAT
aligner: hisat2
asite_disp_length_file: null
buffer: 120
build_indices: true
cmd_file: run_riboviz_M-Ca_2014.sh
codon_positions_file: null
count_reads: true
count_threshold: 64
dataset: M-Ca_2014
dedup_stats: false
dedup_umis: false
dir_in: M-Ca_2014/input
dir_index: M-Ca_2014/index
dir_logs: M-Ca_2014/logs
dir_out: M-Ca_2014/output
dir_tmp: M-Ca_2014/tmp
do_pos_sp_nt_freq: false
extract_umis: false
features_file: null
fq_files:
  WT_A: SRR1027794.fastq.gz
  WT_A2: SRR1027795.fastq.gz
  WT_B: SRR1027796.fastq.gz
group_umis: false
is_riboviz_gff: true
is_test_run: false
make_bedgraph: true
max_read_length: 50
min_read_length: 10
multiplex_fq_files: null
num_processes: 8
orf_fasta_file: ../../riboviz/example-datasets/fungi/candida/annotation/Candida_albicans_CDS_with_120utrs.fa
orf_gff_file: ../../riboviz/example-datasets/fungi/candida/annotation/Candida_albicans_CDS_with_120utrs.gff3
orf_index_prefix: CAlbi_CDS_with_120utrs
primary_id: Name
publish_index_tmp: false
rpf: true
rrna_fasta_file: ../../riboviz/example-datasets/fungi/candida/contaminants/Candida_albicans_rRNA_tRNA.fa
rrna_index_prefix: Calbicans_rRNA_tRNA
sample_sheet: null
secondary_id: null
stop_in_cds: true
t_rna_file: null
trim_5p_mismatches: true
umi_regexp: null
