{dir_in: EIRNA_2023/input, dir_out: EIRNA_2023/output, dataset: EIRNA_2023_LK_down,
  fq_files: null, sample_sheet: ../../../example-datasets/fungi/lachancea/EIRNA_2023_barcodes.tsv,
  features_file: /exports/csce/eddie/biology/groups/wallace_rna/riboviz-david/riboviz/riboviz/data/yeast_features.tsv}

